name: Dependency Graph
on:
  push:
    branches:
      - main

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  dependency-graph:
    name: Submit dependencies to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: sbt/setup-sbt@v1
      - name: Set current timestamp (to the minute)
        run: echo "TIMESTAMP_MINUTE=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_ENV
      - uses: mkurz/sbt-dependency-submission@overrides # for root project
        id: submit-root-build
        with:
          correlator: '${{ github.workflow }}_${{ github.job }}_${{ github.action }}-branch_${{ github.ref_name }}'
          manifest-override: '${{ env.TIMESTAMP_MINUTE }} [${{ github.ref_name}}] build.sbt'
          # By hardcoding the sha and ref, we ensure that all branches update the same snapshots, differing only by their correlator.
          sha-override: 'c777436a26358f81dbfbd3e715d7a128bffa4427'
          ref-override: 'refs/heads/main' #  2025-02-27: GitHub ignores it, but to be future-proof, let's hardcode it (not using github.event.repository.default_branch)
          configs-ignore: provided optional compile-internal test-internal runtime-internal scala-tool scala-doc-tool scripted-sbt scripted-sbt-launch jmh webjars
          sbt-plugin-version: '3.3.0-SNAPSHOT'
      - name: Log dependency snapshot for build.sbt
        run: cat ${{ steps.submit-root-build.outputs.snapshot-json-path }} | jq
      - uses: mkurz/sbt-dependency-submission@overrides
        id: submit-documentation-build
        with:
          working-directory: './documentation/'
          correlator: '${{ github.workflow }}_${{ github.job }}_${{ github.action }}-branch_${{ github.ref_name }}'
          manifest-override: '${{ env.TIMESTAMP_MINUTE }} [${{ github.ref_name}}] documentation/build.sbt'
          # By hardcoding the sha and ref, we ensure that all branches update the same snapshots, differing only by their correlator.
          sha-override: 'c777436a26358f81dbfbd3e715d7a128bffa4427'
          ref-override: 'refs/heads/main' #  2025-02-27: GitHub ignores it, but to be future-proof, let's hardcode it (not using github.event.repository.default_branch)
          configs-ignore: provided optional compile-internal test-internal runtime-internal scala-tool scala-doc-tool scripted-sbt scripted-sbt-launch jmh webjars
          sbt-plugin-version: '3.3.0-SNAPSHOT'
      - name: Log dependency snapshot for documentation/build.sbt
        run: cat ${{ steps.submit-documentation-build.outputs.snapshot-json-path }} | jq
